[package]
name = "nogame"
version = "0.1.0"
cairo-version = "^2.1.0-rc4"
authors = ["ametel01"]
license = "MIT"

[dependencies]
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", branch = "cairo-2" }

starknet = "^2.1.0-rc4"

[[target.starknet-contract]]
sierra = true
casm = true
# [scripts]
# test = "cairo-test ."

# [lib]
# sierra = true
# casm = false