[package]
name = "nogame"
version = "0.1.0"
authors = ["ametel01"]
license = "MIT"
edition = '2023_01'

[dependencies]
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.8.0" }
nogame_fixed = {git = "https://github.com/ametel01/nogame-fixed.git", rev="5317597"}
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
starknet = "2.4.3"

[dev-dependencies]

[scripts]
test = "snforge test"
declare = "sh scripts/sepolia/declare.sh"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true

[tool.snforge]
exit_first = false

[tool.sncast.goerli]
account = "scripts/goerli/goerli-account.json"
accounts-file = "/Users/alexmetelli/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/25371764a3e44191b39d3b3b98a8c55d"
