[package]
name = "nogame"
version = "0.1.0"
authors = ["ametel01"]
license = "MIT"
edition = "2023_01"

[scripts]
test = "snforge test"

[dependencies]
starknet = "2.4.0"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.8.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
nogame_fixed = {git = "https://github.com/ametel01/nogame-fixed.git", rev="5317597"}

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
# build-external-contracts = ["openzeppelin::token::erc20::erc20::ERC20" ]
sierra = true
casm = true

[tool.snforge]
exit_first = false

