[package]
name = "nogame"
version = "0.1.0"
cairo-version = "2.1.0-rc4"
authors = ["ametel01"]
license = "MIT"

[dependencies]
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", branch = "cairo-2" }
starknet = "2.1.0-rc4"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "all"
build-external-contracts = ["openzeppelin::token::erc20::erc20::ERC20"]
sierra = true
casm = true

[tool.snforge]
exit_first = true

# [lib]
# sierra = true  # Enable Sierra codegen.
# casm = true   # Enable CASM codegen.
# [scripts]
# test = "cairo-test ."

# [lib]
# sierra = true
# casm = false