[package]
name = "nogame"
version = "0.1.0"
authors = ["ametel01"]
license = "MIT"
edition = '2023_01'

[dependencies]
openzeppelin = { git = "https://github.com/ametel01/cairo-contracts.git", rev="8641873" }
nogame_fixed = {git = "https://github.com/ametel01/nogame-fixed.git", rev="5317597"}
starknet = "2.5.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.18.0" }

[tool.fmt]
sort-module-level-items = true

[scripts]
test = "snforge test"
declare = "sh scripts/sepolia/declare.sh"
deploy = "sh scripts/sepolia/deploy.sh"
len = "sh scripts/sierra_len.sh"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true

[tool.snforge]
exit_first = false

