[package]
name = "nogame"
version = "0.1.0"
authors = ["ametel01"]
license = "MIT"
edition = "2023_01"

[scripts]
test = "snforge test"

[dependencies]
starknet = "2.4.1"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.8.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
nogame_fixed = {git = "https://github.com/ametel01/nogame-fixed.git", rev="5317597"}


[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
build-external-contracts = ["openzeppelin::token::erc20::erc20::ERC20" ]
sierra = true
casm = true

[tool.snforge]
exit_first = false

[tool.sncast.katana]
account = "k_acc"
accounts-file = "/Users/alexmetelli/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://0.0.0.0:5050"

[tool.sncast.testnet]
account = "cast_testnet"
accounts-file = "/Users/alexmetelli/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/25371764a3e44191b39d3b3b98a8c55d"
