name: CI
on:
    push:
    merge_group:
    pull_request:
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: software-mansion/setup-scarb@v1.1.0
              with:
                  scarb-version: "0.7.0"
            - run: scarb fmt --check
