name: Test

on: [push, pull_request]

env:
  SCARB_VERSION: 2.4.3
  SNFORGE_VERSION: 0.13.1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: ${{ env.SNFORGE_VERSION }}
      - name: Run cairo tests
        run: 
          snforge test